### PR TITLE
Update to wasmtime 18

### PR DESCRIPTION
**Pull request by kayhhh**
Change `WasiView` methods, rename `Table` -> `ResourceTable`, bring WASI up to 0.2.0

This branch builds on https://github.com/kajacx/wasm-bridge/pull/12 as it made testing easier for myself but can remove those changes if there are issue.

### CODE REVIEW

**Comment by kayhhh** [comment]
ok not gonna lie i thought this would be easier this might be beyond my knowledge i have no clue if any of this is correct

**Comment by kayhhh** [comment]
well as i say that i now have a wasi 2.0 component that runs both native and in the browser so it at least seems to be working for my use case

**Comment by kajacx** [comment]
Updating to a new version of wasmtime feels like playing whack-a-mole, by the time the update is done a new version is out already. TBH I am glad the code is working as it is (especially the WASI stuff), but I can look into the update sometime (hopefully) soon.

**Comment by kajacx** [comment]
Hello, I finally got around to it this week. I went ahead and updated to wasmtime 19.0 in version 0.4.0, which should be on crates.io by now. Thanks for putting in the work!

**Comment by kajacx** [comment]
UPDATE: I cannot seem to publish the wasm-bridge-wasi crate to crates.io, so you can use a git dependency at the `v0.4.0` tag instead until I solve it.

**Pull request closed without merging**
